### ISSUE TITLE
Error "Dot indexing is not supported" from advanced queries

### ISSUE THREAD

**Issue by hoodkyle** [micahjsmith/bls-matlab#1]
Note: I'm using Matlab R2019a on a server.

The first time I tried to use the package, I an error when running the following code (<<>> indicates that I had to redact the information):

```
d = '<<some_path>>\inputdata\';
path1 = genpath(d) ;
path(path1,path) ;

APIKey = '<<my api key>>' ;

b = bls([], APIKey);
data = fetch(b, 'PRS85006092', 'catalog', 'true');

```
The error I got was the following (note, it traces the error from the original Matlab test script, Untitled2.m):

> Dot indexing is not supported for variables of this type.
> 
> Error in bls/fetch>blsExtractDataField (line 127)
>   value = str2double(field.value);
> 
> Error in bls/fetch (line 116)
>     data = arrayfun(@blsExtractDataField, ...
> 
> Error in Untitled2 (line 14)
> data = fetch(b, 'PRS85006092', 'catalog', 'true');

It seems the error could be traced to the command (around line 116):
```
        data = arrayfun(@blsExtractDataField, ...
                    response.Results.series(iSeries).data, 'un', 0);

```
I was able to modify the "fetch" command with the following code replacing the above:
```
    try
        data = arrayfun(@blsExtractDataField, ...
                    response.Results.series(iSeries).data, 'un', 0);
    catch
        data = cellfun(@blsExtractDataField, ...
                    response.Results.series(iSeries).data, 'un', 0);
    end
```
This seems to have solved the issue, although I am not sure how.

**Comment by micahjsmith** [comment]
Thanks for reporting @hoodkyle! Looking into this now.
