### ISSUE TITLE
does not run

### ISSUE THREAD

**Issue by DEFc0r** [micahjsmith/bls-matlab#2]
I used your class file and the function. I created a main and typed
 b = bls([], I put my API key here);
data = fetch(b, 'PRS85006092', 'catalog', 'true');

I got this message 

File: main.m Line: 1 Column: 15
Invalid expression. Check for missing multiplication operator, missing or unbalanced delimiters, or other syntax
error. To construct matrices, use brackets instead of parentheses.

**Comment by micahjsmith** [comment]
@DEFc0r what version of matlab are you using?

I no longer code in matlab or have access to a license at the moment. if you'd think you've found an issue due to a new version of matlab with breaking syntax changes, please feel free to propose a PR

**Comment by micahjsmith** [comment]
@DEFc0r please feel free to reopen if you are able to share details about your error and environment!
